### ISSUE TITLE
npm ERR! Found: postcss-load-config@4.0.1

### ISSUE THREAD

**Issue by goodforever** [spences10/graphcms-sveltekit-portfolio-and-blog-starter#65]
ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: svelte-preprocess@4.10.6
npm ERR! Found: postcss-load-config@4.0.1
npm ERR! node_modules/postcss-load-config
npm ERR!   dev postcss-load-config@"4.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional postcss-load-config@"^2.1.0 || ^3.0.0" from svelte-preprocess@4.10.6
npm ERR! node_modules/svelte-preprocess
npm ERR!   dev svelte-preprocess@"4.10.6" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: postcss-load-config@3.1.4
npm ERR! node_modules/postcss-load-config
npm ERR!   peerOptional postcss-load-config@"^2.1.0 || ^3.0.0" from svelte-preprocess@4.10.6
npm ERR!   node_modules/svelte-preprocess
npm ERR!     dev svelte-preprocess@"4.10.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by spences10** [comment]
Hey @goodforever 

This should be resolved now with https://github.com/spences10/graphcms-sveltekit-portfolio-and-blog-starter/commit/1d06784d0039f3876824f30cea037f59ff8e6f3b

Thanks
